[package]
name = "sequoia-openpgp"
description = "OpenPGP data types and associated machinery"
version = "0.19.0"
authors = [
    "Igor Matuszewski <igor@sequoia-pgp.org>",
    "Justus Winter <justus@sequoia-pgp.org>",
    "Kai Michaelis <kai@sequoia-pgp.org>",
    "Neal H. Walfield <neal@sequoia-pgp.org>",
    "Nora Widdecke <nora@sequoia-pgp.org>",
    "Wiktor Kwapisiewicz <wiktor@sequoia-pgp.org>",
]
build = "build.rs"
documentation = "https://docs.sequoia-pgp.org/0.19.0/sequoia_openpgp"
homepage = "https://sequoia-pgp.org/"
repository = "https://gitlab.com/sequoia-pgp/sequoia"
readme = "README.md"
keywords = ["cryptography", "openpgp", "pgp", "encryption", "signing"]
categories = ["cryptography", "authentication", "email"]
license = "GPL-2.0-or-later"
edition = "2018"

[badges]
gitlab = { repository = "sequoia-pgp/sequoia" }
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = "1"
buffered-reader = { path = "../buffered-reader", version = "0.18", default-features = false }
base64 = ">= 0.11, < 0.13"
bzip2 = { version = "0.3.2", optional = true }
# dyn-clone = "1"
dyn-clone = ">= 1.0.1, < 1.0.2" # Pinned, see below.
flate2 = { version = "1.0.1", optional = true }
idna = "0.2"
lalrpop-util = "0.19"
lazy_static = "1.3"
libc = "0.2"
memsec = "0.5.6"
nettle = { version = "7", optional = true }
regex = "1"
thiserror = "1"
backtrace = "0.3.46"
unicode-normalization = "0.1.9"

[target.'cfg(windows)'.dependencies]
win-crypto-ng = { version = "0.2", features = ["rand"], optional = true }
num-bigint-dig = { version = "0.6", default-features = false, optional = true }
# rand feature is unnecessarily required, see https://github.com/dalek-cryptography/ed25519-dalek/pull/139
ed25519-dalek = { version = "1", default-features = false, features = ["rand", "u64_backend"], optional = true }
winapi = { version = "0.3", default-features = false, features = ["bcrypt"], optional = true }

[build-dependencies]
lalrpop = "0.19"

[dev-dependencies]
quickcheck = { version = "0.9", default-features = false }
rand = { version = "0.7", default-features = false }
rpassword = "5.0"

[features]
default = ["compression", "crypto-cng"]
# TODO(#333): Allow for/implement more backends
crypto-cng = ["winapi", "win-crypto-ng", "ed25519-dalek", "num-bigint-dig"]

# The compression algorithms.
compression = ["compression-deflate", "compression-bzip2"]
compression-deflate = ["flate2", "buffered-reader/compression-deflate"]
compression-bzip2 = ["bzip2", "buffered-reader/compression-bzip2"]

# Vendoring.
vendored = ["vendored-nettle"]
vendored-nettle = ["nettle/vendored"]

[[example]]
name = "pad"
required-features = ["compression-deflate"]
