stages:
  - pre-check
  - build
  - test

before_script:
  - if [ -d $CARGO_TARGET_DIR ]; then find $CARGO_TARGET_DIR | wc --lines; du -sh $CARGO_TARGET_DIR; fi
  - if [ -d $CARGO_HOME ]; then find $CARGO_HOME | wc --lines; du -sh $CARGO_HOME; fi
  - rustc --version
  - cargo --version
  - clang --version

after_script:
  - if [ -d $CARGO_TARGET_DIR ]; then find $CARGO_TARGET_DIR -type f -atime +7 -delete; fi
  - if [ -d $CARGO_TARGET_DIR ]; then du -sh $CARGO_TARGET_DIR; fi
  - if [ -d $CARGO_HOME ]; then du -sh $CARGO_HOME; fi

build-bullseye:
  tags:
    - linux
  stage: build
  image: registry.gitlab.com/sequoia-pgp/build-docker-image/bullseye-prebuild:latest
  dependencies:
    - codespell
  script:
    - make
    - if ! git diff --quiet Cargo.lock ; then echo "Cargo.lock changed.  Please add the change to the corresponding commit." ; false ; fi
    - if ! git diff --quiet sq ; then echo "Please commit the changes to sq/src/sq-usage.rs." ; false ; fi
    - if ! git diff --quiet sqv ; then echo "Please commit the changes to sqv/src/sqv-usage.rs." ; false ; fi
    - if ! git diff --quiet ; then echo "The build changed the source.  Please investigate." ; git diff ; fi
  variables:
    CARGO_TARGET_DIR: /target
    CARGO_HOME: /cargo
    RUSTFLAGS: -D warnings -A unused-parens
  after_script: []

bullseye:
  tags:
    - linux
  stage: build
  image: registry.gitlab.com/sequoia-pgp/build-docker-image/bullseye-prebuild:latest
  dependencies:
    - codespell
  script:
    - SEQUOIA_CTEST_VALGRIND=/usr/bin/valgrind make test
  variables:
    CARGO_TARGET_DIR: /target
    CARGO_HOME: /cargo
    RUSTFLAGS: -D warnings -A unused-parens
  after_script: []

codespell:
  tags:
    - linux
  stage: pre-check
  image: registry.gitlab.com/sequoia-pgp/build-docker-image/bullseye:latest

  before_script:
    - codespell --version
  script:
    - make codespell CODESPELL_FLAGS=--summary
  after_script: []

rust-stable:
  tags:
    - linux
  stage: build
  image: registry.gitlab.com/sequoia-pgp/build-docker-image/rust-stable-prebuild:latest
  script:
    - CARGO_PACKAGES="-p buffered-reader -p sequoia-openpgp -p sequoia-sqv" make test
    - mkdir -p tested_commits
    # Mark this commit sha as succesfully run, for all_commits.
    - echo $CI_JOB_URL >> tested_commits/$CI_COMMIT_SHA
  variables:
    CARGO_TARGET_DIR: /target
    CARGO_HOME: /cargo
    RUSTFLAGS: -D warnings -A unused-parens
  artifacts:
    paths:
      - tested_commits
    expire_in: 1 week

# Only test commits once in all_commits.
# When a commit has been tested we keep track of it by touching a file named by
# the commit sha in tested_commits.
# Before running the tests we check if such a file exists.
# We store these files as artifacts and load them before runs on the same branch.
all_commits:
  # Test each commit up to main, to facilitate bisecting.
  stage: test
  image: registry.gitlab.com/sequoia-pgp/build-docker-image/rust-stable-prebuild:latest
  needs: ["rust-stable"]
  except:
    # Do not run for pushes to the pep-engine branch.
    - /^pep-engine$/
    # We have a strict farst-forward-merge policy, all commits have been tested by
    # this job on the source branche anyway.
    - master
  script:
    - echo $ARTIFACTS
    - 'curl -sL -o artifacts.zip -H "JOB-TOKEN: $CI_JOB_TOKEN" "$ARTIFACTS"'
    - unzip -n artifacts.zip || echo "No previous runs found."
    - if [ -d tested_commits ]; then ls tested_commits; fi
    - .ci/all_commits.sh
    - if [ -d tested_commits ]; then ls tested_commits; fi
  variables:
    CARGO_TARGET_DIR: /target
    CARGO_HOME: /cargo
    RUSTFLAGS: -D warnings -A unused-parens
    GIT_STRATEGY: clone
    ARTIFACTS: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_COMMIT_BRANCH/download?job=all_commits"
  artifacts:
    paths:
      - tested_commits
    expire_in: 1 week

windows-gnu:
  tags:
    - win
    - win2019
  stage: build
  image: registry.gitlab.com/sequoia-pgp/build-docker-image/windows-gnu
  # This job takes ~20 minutes to run, let's only execute it manually or for
  # scheduled builds, otherwise this will stall MRs often not related to Windows
  only:
    - /windows/i # refs containing 'windows' keyword
    - tags
    - web
    - scheduled
  before_script:
    - clang -v
    - rustc --version --verbose
    - cargo --version
  script:
    - cargo test --all --exclude sequoia-openpgp-ffi
    # https://github.com/rust-lang/cargo/issues/5015
    - cargo test --manifest-path openpgp/Cargo.toml --no-default-features --features crypto-cng,compression
  after_script: []
  variables:
    CFLAGS: "" # Silence some C warnings when compiling under Windows

windows-msvc:
  tags:
    - win
    - win2019
  stage: build
  image: registry.gitlab.com/sequoia-pgp/build-docker-image/windows-msvc
  before_script:
    - rustc --version --verbose
    - cargo --version
  script:
    # https://github.com/rust-lang/cargo/issues/5015
    - cargo build --manifest-path ffi/Cargo.toml --no-default-features --features crypto-cng,compression
    - cargo build --manifest-path openpgp-ffi/Cargo.toml --no-default-features --features crypto-cng,compression
    - cargo test --manifest-path openpgp/Cargo.toml --no-default-features --features crypto-cng,compression
  after_script: []
  variables:
    CFLAGS: "" # Silence some C warnings when compiling with MSVC

variables:
  DEBIAN_FRONTEND: noninteractive
  CARGO_HOME: $CI_PROJECT_DIR/../cargo
  CARGO_FLAGS: --color always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings
  CFLAGS: -Werror
  QUICKCHECK_GENERATOR_SIZE: 500 # https://github.com/BurntSushi/quickcheck/pull/240
