test-caching:
  image: rust:latest
  before_script:
    - mkdir -p cache_me
    - ls -lah cache_me
  script:
    - touch cache_me/exhibit_a
  after_script:
    - ls -lah cache_me
  cache:
    paths:
      - cache_me
    key: i_m_just_here_to_test_the_cache
