[package]
name = "sequoia-secret"
version = "0.1.0"
authors = ["Justus Winter <justus@sequoia-pgp.org>"]
build = "build.rs"

[features]
default = ["background-services"]
background-services = []

[dependencies]
openpgp = { path = "../openpgp" }
sequoia-core = { path = "../core" }
sequoia-net = { path = "../net" }

capnp = "0.8"
capnp-rpc = "0.8"
failure = "0.1.1"
futures = "0.1.17"
rusqlite = "0.12.0"
time = "0.1.38"
tokio-core = "0.1.10"
tokio-io = "0.1.4"

[build-dependencies]
capnpc = "0.8"

[lib]
name = "sequoia_secret"
path = "src/lib.rs"

[[bin]]
name = "secret-store"
path = "src/server.rs"
doc = false
required-features = ["background-services"]
